### ISSUE TITLE
Всё падает

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#502]
```
Running "nodeunit:all" (nodeunit) task
Testing health-check.js.OK
Testing health-check.coffee.OK
Testing game.coffee[Error: While performing createIndex 
[,[object Object],uniusers,sessid]
error: отношение "uniusers_sessid" уже существует
Error
  at PostgresConnection.conn.query (/data/m1kc/Проекты/Project Universe/uonline/tests/game.coffee:128:24)
  at exports.createIndex (/data/m1kc/Проекты/Project Universe/uonline/lib-cov/tables.js:283:22)
  at Function.sync (/data/m1kc/Проекты/Project Universe/uonline/node_modules/sync/lib/sync.js:69:10)
  at justMigrate (/data/m1kc/Проекты/Project Universe/uonline/lib-cov/migration.js:302:31)
  at Object.<anonymous> (/data/m1kc/Проекты/Project Universe/uonline/lib-cov/migration.js:486:17)
  at Function.asyncFunction.sync (/data/m1kc/Проекты/Project Universe/uonline/node_modules/sync/lib/sync.js:386:19)
  at Object.<anonymous> (/data/m1kc/Проекты/Project Universe/uonline/tests/game.coffee:15:2)
  at /data/m1kc/Проекты/Project Universe/uonline/node_modules/sync/lib/sync.js:368:27
  at /data/m1kc/Проекты/Project Universe/uonline/node_modules/sync/lib/sync.js:178:22
]
........................................OK
Testing locparse.coffee...................OK
Testing locparse_utils.coffee.........OK
Testing math.coffee.OK
Testing migration.coffee.............OK
Testing prettyprint.coffee......OK
Testing query_utils.coffee.....OK
Testing tables.coffee...........OK
Testing user.coffeeF.............
>> userExists
>> Error: While performing createIndex 
>> [,[object Object],uniusers,sessid]
>> error: отношение "uniusers_sessid" уже существует
>> error: отношение "uniusers_sessid" уже существует
>>   at [object Object].Connection.parseE (node_modules/any-db-postgres/node_modules/pg.js/lib/connection.js:534:11)
>>   at [object Object].Connection.parseMessage (node_modules/any-db-postgres/node_modules/pg.js/lib/connection.js:361:17)
>>   at Socket.<anonymous> (node_modules/any-db-postgres/node_modules/pg.js/lib/connection.js:105:22)
>>   at Socket.emit (events.js:107:17)
>>   at readableAddChunk (_stream_readable.js:163:16)
>>   at Socket.Readable.push (_stream_readable.js:126:10)
>>   at TCP.onread (net.js:529:20)
>> 
>>   at justMigrate (lib-cov/migration.js:310:23)
>>   at Object.<anonymous> (lib-cov/migration.js:486:17)
>>   at Function.asyncFunction.sync (node_modules/sync/lib/sync.js:386:19)
>>   at Object.<anonymous> (tests/user.coffee:127:15)
>>   at /data/m1kc/Проекты/Project Universe/uonline/node_modules/sync/lib/sync.js:368:27
>>   at /data/m1kc/Проекты/Project Universe/uonline/node_modules/sync/lib/sync.js:178:22

Testing validation.coffee...OK
Warning: 1/675 assertions failed (24248ms) Use --force to continue.

Aborted due to warnings.

**Comment by 3bl3gamer** [comment]
Вроде бы больше не падает https://github.com/uonline/uonline/commit/ad74d7d6144f7f881aa55eeb962c230ee18f45b0.
