### ISSUE TITLE
source maps

### ISSUE THREAD

**Issue by m1kc** [uonline/uonline#522]
@3bl3gamer, у нас есть сейчас где-нибудь проблемы с нумерацией строк? Ну типа номера едут или ссылаются на JS вместо кофе.

**Comment by 3bl3gamer** [comment]
Не замечал с момента появления карточки.

Но писать малоинформативную фигню вместо стректрейсов оно продолжает с тем же упорством.

Например:
```
Caught exception: TypeError: undefined is not a function
  at Object.exports._hitAndGetHealth (evalmachine.<anonymous>:599:19)
  at Object.exports._hitAndGetHealth.simple (/home/zblzgamer/git/uonline/tests/game.coffee:518:14)
...
```
Да, `undefined is not a function`, да через `tests/game.coffee:518` эксепшен пролетал. Вот только вывалился он в `lib/game.coffee:371`, что из трейса как-то нифига не ясно.

Не уверен, что это с map'ами связно, но мало ли.

**Comment by m1kc** [comment]
@3bl3gamer Так, погоди. А весь трейс кинуть можешь?

**Comment by 3bl3gamer** [comment]
Могу:
```
Caught exception: TypeError: undefined is not a function
  at Object.exports._hitAndGetHealth (evalmachine.<anonymous>:599:19)
  at Object.exports._hitAndGetHealth.simple (/home/zblzgamer/git/uonline/tests/game.coffee:518:14)
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/lib/core.js:232:20
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:168:13
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:131:25
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:165:17
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:463:34
  at Object.exports._hitAndGetHealth.setUp (/home/zblzgamer/git/uonline/tests/game.coffee:504:3)
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/lib/core.js:260:35
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:458:21
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:163:13
  at iterate (/home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:123:13)
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:134:25
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:165:17
  at /home/zblzgamer/git/uonline/node_modules/nodeunit/deps/async.js:463:34
  at /home/zblzgamer/git/uonline/node_modules/sync/lib/sync.js:190:13
```

**Comment by m1kc** [comment]
@3bl3gamer Завтра буду читать исходники этих замечательных библиотек. Мне кажется, одна из них исключение хоронит и откуда-то изнутри заново кидает.
